### ISSUE TITLE
Getting errors when trying to load these mods.

### ISSUE THREAD

**Issue by DOiJRP** [Spaceman/ConsoleCommands#1]
States the error that this mod is a client mod so "user/mods" folder will not load the mods and is saying that it should be in "/spt/bepinex/plugins" which I made the folder but the mod doesn't work.
![Screenshot 2024-05-12 221427](https://github.com/LostQuasar/ConsoleCommands/assets/66528786/2dddc7ef-2326-470e-bbcd-8cdefdbb413e)

**Comment by LostQuasar** [comment]
This mod is three years old you are welcome to attempt to fix it but I will not be providing support for it
